title: <p align="center"> Sajan Kedia </p>
logo: /assets/img/logo.png
description: Full stack developer and Machine Learning enthusiast
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
