title: <p align="center"> Anirban Gangopadhyay </p>
logo: /assets/img/anirban_1.jpeg
description: Full stack developer and Machine Learning enthusiast
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
